In [ ]:
import numpy as np
import cv2 as cv
import random
import os
import matplotlib.pyplot as plt
import pickle
import keras
%matplotlib inline


In [ ]:
DIRECTORY =  '/content/drive/MyDrive/dataset'
# a raw string(r'...') is used to treat backslash(\) as a normal character
CATEGORIES = ['mammooty','mohanlal']


In [ ]:
IMG_SIZE = 224

data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        label = CATEGORIES.index(category)
        img_arr = cv.imread(img_path)
        img_arr = cv.resize(img_arr,(IMG_SIZE,IMG_SIZE))
        data.append([img_arr,label])
#         labelling the data

In [ ]:
import random
random.shuffle(data)

In [ ]:
X = []
y = []

for features, labels in data:
    X.append(features)
    y.append(labels)

In [ ]:
X = np.array(X)
y = np.array(y)
# changed X & y into arrays and stored it in respective variables

In [ ]:
X

array([[[[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [ 13,  16,  31],
         [ 13,  16,  31],
         [ 13,  16,  31]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [ 13,  16,  31],
         [ 13,  16,  31],
         [ 13,  16,  31]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [ 13,  16,  30],
         [ 13,  16,  30],
         [ 13,  16,  30]],

        ...,

        [[162, 173, 253],
         [162, 173, 253],
         [162, 173, 253],
         ...,
         [ 22,  44, 110],
         [ 19,  41, 107],
         [ 17,  39, 105]],

        [[162, 173, 253],
         [162, 173, 253],
         [162, 173, 253],
         ...,
         [ 21,  43, 109],
         [ 18,  40, 106],
         [ 16,  38, 104]],

        [[162, 173, 253],
         [162, 173, 253],
         [162, 173, 253],
         ...,
         [ 20,  42, 108],
        

In [ ]:
y

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,

In [ ]:
X

array([[[[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [ 13,  16,  31],
         [ 13,  16,  31],
         [ 13,  16,  31]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [ 13,  16,  31],
         [ 13,  16,  31],
         [ 13,  16,  31]],

        [[253, 253, 253],
         [253, 253, 253],
         [253, 253, 253],
         ...,
         [ 13,  16,  30],
         [ 13,  16,  30],
         [ 13,  16,  30]],

        ...,

        [[162, 173, 253],
         [162, 173, 253],
         [162, 173, 253],
         ...,
         [ 22,  44, 110],
         [ 19,  41, 107],
         [ 17,  39, 105]],

        [[162, 173, 253],
         [162, 173, 253],
         [162, 173, 253],
         ...,
         [ 21,  43, 109],
         [ 18,  40, 106],
         [ 16,  38, 104]],

        [[162, 173, 253],
         [162, 173, 253],
         [162, 173, 253],
         ...,
         [ 20,  42, 108],
        

In [ ]:
X = X/255

In [ ]:
X

array([[[[0.99215686, 0.99215686, 0.99215686],
         [0.99215686, 0.99215686, 0.99215686],
         [0.99215686, 0.99215686, 0.99215686],
         ...,
         [0.05098039, 0.0627451 , 0.12156863],
         [0.05098039, 0.0627451 , 0.12156863],
         [0.05098039, 0.0627451 , 0.12156863]],

        [[0.99215686, 0.99215686, 0.99215686],
         [0.99215686, 0.99215686, 0.99215686],
         [0.99215686, 0.99215686, 0.99215686],
         ...,
         [0.05098039, 0.0627451 , 0.12156863],
         [0.05098039, 0.0627451 , 0.12156863],
         [0.05098039, 0.0627451 , 0.12156863]],

        [[0.99215686, 0.99215686, 0.99215686],
         [0.99215686, 0.99215686, 0.99215686],
         [0.99215686, 0.99215686, 0.99215686],
         ...,
         [0.05098039, 0.0627451 , 0.11764706],
         [0.05098039, 0.0627451 , 0.11764706],
         [0.05098039, 0.0627451 , 0.11764706]],

        ...,

        [[0.63529412, 0.67843137, 0.99215686],
         [0.63529412, 0.67843137, 0.99215686]

In [ ]:
X.shape

(994, 224, 224, 3)

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten,GlobalAveragePooling2D
from tensorflow.keras.models import Model



In [ ]:
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.applications.inception_v3 import preprocess_input

base_model = InceptionV3(
    include_top=False,
    weights='imagenet',
    input_shape=(224, 224, 3)
)


87910968/87910968 [==============================] - 0s 0us/step


In [ ]:
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
predictions = Dense(1, activation='sigmoid')(x)
model = Model(inputs=base_model.input, outputs=predictions)

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
y.shape

(994,)

In [ ]:
model.fit(X, y, epochs=5, validation_split=0.2)

Epoch 1/5
25/25 [==============================] - 55s 539ms/step - loss: 0.5393 - accuracy: 0.8377 - val_loss: 54.5422 - val_accuracy: 0.7136
Epoch 2/5
25/25 [==============================] - 7s 265ms/step - loss: 0.1250 - accuracy: 0.9484 - val_loss: 130.7515 - val_accuracy: 0.7136
Epoch 3/5
25/25 [==============================] - 6s 260ms/step - loss: 0.0387 - accuracy: 0.9912 - val_loss: 31.3700 - val_accuracy: 0.7136
Epoch 4/5
25/25 [==============================] - 7s 269ms/step - loss: 0.0181 - accuracy: 0.9962 - val_loss: 3.1706 - val_accuracy: 0.7136
Epoch 5/5
25/25 [==============================] - 7s 264ms/step - loss: 0.0264 - accuracy: 0.9912 - val_loss: 3.0928 - val_accuracy: 0.7136


In [ ]:
model.save('inception v3.model',save_format = 'h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
import numpy as np
import cv2
import keras

In [ ]:
def image(path):
    img = cv2.imread(path, cv2.IMREAD_COLOR)
    new_arr = cv2.resize(img, (224, 224))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 224,224, 3)
    return new_arr
#preprocessing the user input

model = keras.models.load_model('/content/inception v3.model')

result = model.predict([image('/content/newlal.jpg')])
if result[0][0] >1.1:
    prediction = 'mamooty'
else:
    prediction = 'mohanlal'
print (result[0][0])
print(prediction)

1/1 [==============================] - 1s 1s/step
1.0
mohanlal
