In [ ]:
import numpy as np
import cv2 as cv
import random
import os
import matplotlib.pyplot as plt
import pickle
%matplotlib inline
import keras

In [ ]:
DIRECTORY = '/content/drive/MyDrive/dataset'
# a raw string(r'...') is used to treat backslash(\) as a normal character
CATEGORIES = ['mammooty','mohanlal']

In [ ]:
IMG_SIZE = 224

data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        label = CATEGORIES.index(category)
        img_arr = cv.imread(img_path, cv.IMREAD_GRAYSCALE)
        img_arr = cv.resize(img_arr,(IMG_SIZE,IMG_SIZE))
        data.append([img_arr,label])
#         labelling the data

In [ ]:
random.shuffle(data)
# to shuffle the data

In [ ]:
X = []
y = []

for features, labels in data:
    X.append(features)
    y.append(labels)

In [ ]:
X = np.array(X)
y = np.array(y)
# changed X & y into arrays and stored it in respective variables


In [ ]:
X

array([[[ 20,  19,  17, ..., 237, 237, 237],
        [ 19,  18,  17, ..., 236, 236, 236],
        [ 18,  17,  16, ..., 234, 233, 233],
        ...,
        [ 19,  19,  18, ...,  37,  38,  39],
        [ 19,  19,  18, ...,  37,  38,  39],
        [ 19,  19,  18, ...,  37,  38,  39]],

       [[ 21,  21,  22, ..., 112, 105, 105],
        [ 21,  21,  21, ..., 112, 105, 105],
        [ 21,  21,  22, ..., 108, 105, 105],
        ...,
        [ 59,  58,  40, ..., 141, 146, 146],
        [ 79,  78,  56, ..., 135, 140, 140],
        [ 81,  79,  56, ..., 135, 139, 140]],

       [[ 12,  10,   7, ..., 120, 121, 122],
        [ 12,  10,   7, ..., 120, 121, 122],
        [ 12,  10,   7, ..., 120, 121, 122],
        ...,
        [ 17,  17,  18, ...,  25,  25,  26],
        [ 18,  18,  18, ...,  24,  25,  25],
        [ 18,  18,  18, ...,  23,  24,  25]],

       ...,

       [[  2,   2,   1, ..., 241, 241, 241],
        [  2,   2,   1, ..., 241, 241, 241],
        [  3,   3,   2, ..., 240, 240, 240

In [ ]:
y

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,

In [ ]:
X = pickle.dump(X,open('X.pkl', 'wb'))
y = pickle.dump(y,open('y.pkl', 'wb'))

# storing the data in a pickle file

In [ ]:
import pickle

In [ ]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [ ]:
X

array([[[ 20,  19,  17, ..., 237, 237, 237],
        [ 19,  18,  17, ..., 236, 236, 236],
        [ 18,  17,  16, ..., 234, 233, 233],
        ...,
        [ 19,  19,  18, ...,  37,  38,  39],
        [ 19,  19,  18, ...,  37,  38,  39],
        [ 19,  19,  18, ...,  37,  38,  39]],

       [[ 21,  21,  22, ..., 112, 105, 105],
        [ 21,  21,  21, ..., 112, 105, 105],
        [ 21,  21,  22, ..., 108, 105, 105],
        ...,
        [ 59,  58,  40, ..., 141, 146, 146],
        [ 79,  78,  56, ..., 135, 140, 140],
        [ 81,  79,  56, ..., 135, 139, 140]],

       [[ 12,  10,   7, ..., 120, 121, 122],
        [ 12,  10,   7, ..., 120, 121, 122],
        [ 12,  10,   7, ..., 120, 121, 122],
        ...,
        [ 17,  17,  18, ...,  25,  25,  26],
        [ 18,  18,  18, ...,  24,  25,  25],
        [ 18,  18,  18, ...,  23,  24,  25]],

       ...,

       [[  2,   2,   1, ..., 241, 241, 241],
        [  2,   2,   1, ..., 241, 241, 241],
        [  3,   3,   2, ..., 240, 240, 240

In [ ]:
y

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,

In [ ]:
X = X/255

In [ ]:
X

array([[[0.07843137, 0.0745098 , 0.06666667, ..., 0.92941176,
         0.92941176, 0.92941176],
        [0.0745098 , 0.07058824, 0.06666667, ..., 0.9254902 ,
         0.9254902 , 0.9254902 ],
        [0.07058824, 0.06666667, 0.0627451 , ..., 0.91764706,
         0.91372549, 0.91372549],
        ...,
        [0.0745098 , 0.0745098 , 0.07058824, ..., 0.14509804,
         0.14901961, 0.15294118],
        [0.0745098 , 0.0745098 , 0.07058824, ..., 0.14509804,
         0.14901961, 0.15294118],
        [0.0745098 , 0.0745098 , 0.07058824, ..., 0.14509804,
         0.14901961, 0.15294118]],

       [[0.08235294, 0.08235294, 0.08627451, ..., 0.43921569,
         0.41176471, 0.41176471],
        [0.08235294, 0.08235294, 0.08235294, ..., 0.43921569,
         0.41176471, 0.41176471],
        [0.08235294, 0.08235294, 0.08627451, ..., 0.42352941,
         0.41176471, 0.41176471],
        ...,
        [0.23137255, 0.22745098, 0.15686275, ..., 0.55294118,
         0.57254902, 0.57254902],
        [0.3

In [ ]:
X.shape

(994, 224, 224)

In [ ]:
X = X.reshape(-1, 224, 224, 1)

In [ ]:
X.shape

(994, 224, 224, 1)

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [ ]:
# Initialising the CNN
model = Sequential()

In [ ]:
# Step 1 - Convolution
model.add(Conv2D(64,(3,3), activation='relu'))
# Step 2 - Pooling
model.add(MaxPooling2D((2,2)))

# Adding a second convolutional layer
model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPooling2D((2,2)))

# Step 3 - Flattening
model.add(Flatten())

# Step 4 - Full Connection
model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

# Step 5 - Output Layer
model.add(Dense(2, activation= 'sigmoid'))

In [ ]:
# Compiling the CNN
model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit(X, y, epochs=10, validation_split=0.2)

Epoch 1/10
25/25 [==============================] - 136s 5s/step - loss: 1.2408 - accuracy: 0.6214 - val_loss: 0.6006 - val_accuracy: 0.7085
Epoch 2/10
25/25 [==============================] - 128s 5s/step - loss: 0.5862 - accuracy: 0.6994 - val_loss: 0.4777 - val_accuracy: 0.7085
Epoch 3/10
25/25 [==============================] - 130s 5s/step - loss: 0.4070 - accuracy: 0.8239 - val_loss: 0.2999 - val_accuracy: 0.8593
Epoch 4/10
25/25 [==============================] - 129s 5s/step - loss: 0.2234 - accuracy: 0.9069 - val_loss: 0.1635 - val_accuracy: 0.9598
Epoch 5/10
16/25 [==================>...........] - ETA: 43s - loss: 0.1411 - accuracy: 0.9648

KeyboardInterrupt: ignored

In [ ]:
scores = model.evaluate(X,y,verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))
#to know accuracy of model

NameError: ignored

In [ ]:
X.shape

(994, 224, 224, 1)

In [ ]:
model.save('/content/drive/MyDrive/cnn4.model.h5')
#to save the model

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
from tensorflow.keras.preprocessing import image
import numpy as np

img_path = '/content/newlal.jpg'
img = image.load_img(img_path, target_size=(150, 150))
img_array = image.img_to_array(img)
img_array /= 255.0
img_array = np.expand_dims(img_array, axis=0)


In [ ]:
from tensorflow.keras.models import load_model

# Load the pre-trained model
loaded_model = load_model('/content/drive/MyDrive/cnn4.model')




In [ ]:
CATEGORIES = ['mammooty', 'mohanlal']


def image(path):
    img = cv.imread(path, cv.IMREAD_GRAYSCALE)
    new_arr = cv.resize(img, (224, 224))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 224,224, 1)
    return new_arr
#preprocessing the user input

In [ ]:
model = keras.models.load_model('/content/drive/MyDrive/cnn4.model')

In [ ]:
result =model.predict([image('/content/newlal.jpg')])
if result[0][0] == 1:
    prediction = 'mamooty'
else :
    prediction = 'mohanlal'
print(prediction)

1/1 [==============================] - 0s 135ms/step
mohanlal
