In [ ]:
import numpy as np
import cv2 as cv
import random
import os
import matplotlib.pyplot as plt
import pickle
import keras
%matplotlib inline


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
DIRECTORY =  '/content/drive/MyDrive/dataset'
# a raw string(r'...') is used to treat backslash(\) as a normal character
CATEGORIES = ['mammooty','mohanlal']


In [ ]:
IMG_SIZE = 224

data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        label = CATEGORIES.index(category)
        img_arr = cv.imread(img_path)
        img_arr = cv.resize(img_arr,(IMG_SIZE,IMG_SIZE))
        data.append([img_arr,label])
#         labelling the data

In [ ]:
import random
random.shuffle(data)

In [ ]:
X = []
y = []

for features, labels in data:
    X.append(features)
    y.append(labels)

In [ ]:
X = np.array(X)
y = np.array(y)
# changed X & y into arrays and stored it in respective variables

In [ ]:
X

array([[[[ 50,  37,  15],
         [ 51,  38,  16],
         [ 54,  40,  20],
         ...,
         [ 64,  57,  64],
         [ 77,  72,  78],
         [ 82,  78,  84]],

        [[ 48,  35,  13],
         [ 49,  35,  14],
         [ 50,  37,  17],
         ...,
         [ 65,  58,  64],
         [ 77,  72,  78],
         [ 82,  78,  84]],

        [[ 44,  30,   8],
         [ 43,  30,   8],
         [ 42,  29,   9],
         ...,
         [ 66,  58,  64],
         [ 78,  72,  77],
         [ 83,  77,  83]],

        ...,

        [[252, 255, 251],
         [252, 255, 251],
         [254, 255, 252],
         ...,
         [195, 210, 200],
         [186, 204, 198],
         [183, 202, 197]],

        [[251, 255, 252],
         [252, 255, 252],
         [253, 255, 252],
         ...,
         [186, 205, 197],
         [176, 198, 193],
         [172, 195, 192]],

        [[251, 255, 252],
         [251, 255, 252],
         [252, 255, 252],
         ...,
         [182, 203, 196],
        

In [ ]:
y

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,

In [ ]:
X

array([[[[ 50,  37,  15],
         [ 51,  38,  16],
         [ 54,  40,  20],
         ...,
         [ 64,  57,  64],
         [ 77,  72,  78],
         [ 82,  78,  84]],

        [[ 48,  35,  13],
         [ 49,  35,  14],
         [ 50,  37,  17],
         ...,
         [ 65,  58,  64],
         [ 77,  72,  78],
         [ 82,  78,  84]],

        [[ 44,  30,   8],
         [ 43,  30,   8],
         [ 42,  29,   9],
         ...,
         [ 66,  58,  64],
         [ 78,  72,  77],
         [ 83,  77,  83]],

        ...,

        [[252, 255, 251],
         [252, 255, 251],
         [254, 255, 252],
         ...,
         [195, 210, 200],
         [186, 204, 198],
         [183, 202, 197]],

        [[251, 255, 252],
         [252, 255, 252],
         [253, 255, 252],
         ...,
         [186, 205, 197],
         [176, 198, 193],
         [172, 195, 192]],

        [[251, 255, 252],
         [251, 255, 252],
         [252, 255, 252],
         ...,
         [182, 203, 196],
        

In [ ]:
X = X/255

In [ ]:
X

array([[[[0.19607843, 0.14509804, 0.05882353],
         [0.2       , 0.14901961, 0.0627451 ],
         [0.21176471, 0.15686275, 0.07843137],
         ...,
         [0.25098039, 0.22352941, 0.25098039],
         [0.30196078, 0.28235294, 0.30588235],
         [0.32156863, 0.30588235, 0.32941176]],

        [[0.18823529, 0.1372549 , 0.05098039],
         [0.19215686, 0.1372549 , 0.05490196],
         [0.19607843, 0.14509804, 0.06666667],
         ...,
         [0.25490196, 0.22745098, 0.25098039],
         [0.30196078, 0.28235294, 0.30588235],
         [0.32156863, 0.30588235, 0.32941176]],

        [[0.17254902, 0.11764706, 0.03137255],
         [0.16862745, 0.11764706, 0.03137255],
         [0.16470588, 0.11372549, 0.03529412],
         ...,
         [0.25882353, 0.22745098, 0.25098039],
         [0.30588235, 0.28235294, 0.30196078],
         [0.3254902 , 0.30196078, 0.3254902 ]],

        ...,

        [[0.98823529, 1.        , 0.98431373],
         [0.98823529, 1.        , 0.98431373]

In [ ]:
X.shape

(994, 224, 224, 3)

In [ ]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam

In [ ]:
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))


94765736/94765736 [==============================] - 0s 0us/step


In [ ]:
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
predictions = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=predictions)

In [ ]:
model = Model(inputs=base_model.input, outputs=predictions)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [ ]:
y.shape

(994,)

In [ ]:
model.fit(X, y, epochs=5, validation_split=0.2)

Epoch 1/5
25/25 [==============================] - 55s 532ms/step - loss: 0.3611 - accuracy: 0.9170 - val_loss: 134.9644 - val_accuracy: 0.7186
Epoch 2/5
25/25 [==============================] - 9s 343ms/step - loss: 0.0544 - accuracy: 0.9836 - val_loss: 1.5230 - val_accuracy: 0.2814
Epoch 3/5
25/25 [==============================] - 9s 342ms/step - loss: 0.0510 - accuracy: 0.9862 - val_loss: 2.0092 - val_accuracy: 0.2814
Epoch 4/5
25/25 [==============================] - 9s 347ms/step - loss: 0.0202 - accuracy: 0.9937 - val_loss: 0.8414 - val_accuracy: 0.2814
Epoch 5/5
25/25 [==============================] - 9s 350ms/step - loss: 0.0453 - accuracy: 0.9824 - val_loss: 0.5960 - val_accuracy: 0.7186


In [ ]:
model.save('resnet.model',save_format = 'h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
import numpy as np
import cv2
import keras

In [ ]:
def image(path):
    img = cv2.imread(path, cv2.IMREAD_COLOR)
    new_arr = cv2.resize(img, (224, 224))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 224,224, 3)
    return new_arr
#preprocessing the user input
model = keras.models.load_model('/content/resnet.model')
result = model.predict([image('/content/newlal.jpg')])


if result[0][0] >0.9:
    prediction = 'mamooty'
else:
    prediction = 'mohanlal'

print(prediction)

1/1 [==============================] - 1s 1s/step
mohanlal
