In [ ]:
import numpy as np
import cv2 as cv
import random
import os
import matplotlib.pyplot as plt
import pickle
import keras
import tensorflow as tf
%matplotlib inline


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
DIRECTORY = r'/content/drive/MyDrive/dataset'
# a raw string(r'...') is used to treat backslash(\) as a normal character
CATEGORIES = ['mammooty','mohanlal']


In [ ]:
IMG_SIZE = 224

data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        label = CATEGORIES.index(category)
        img_arr = cv.imread(img_path)
        img_arr = cv.resize(img_arr,(IMG_SIZE,IMG_SIZE))
        data.append([img_arr,label])
#         labelling the data

In [ ]:
import random
random.shuffle(data)

In [ ]:
X = []
y = []

for features, labels in data:
    X.append(features)
    y.append(labels)

In [ ]:
X = np.array(X)
y = np.array(y)
# changed X & y into arrays and stored it in respective variables

In [ ]:
X

array([[[[  3,   2,   4],
         [  3,   2,   4],
         [  3,   2,   4],
         ...,
         [ 11,   9,   9],
         [ 10,   8,   8],
         [ 10,   8,   8]],

        [[  3,   2,   4],
         [  3,   2,   4],
         [  4,   3,   5],
         ...,
         [ 11,   9,   9],
         [ 10,   8,   8],
         [ 10,   8,   8]],

        [[  3,   2,   4],
         [  3,   2,   4],
         [  4,   3,   5],
         ...,
         [ 11,   9,   9],
         [ 10,   8,   8],
         [ 10,   8,   8]],

        ...,

        [[ 28,  36,  66],
         [ 28,  36,  66],
         [ 28,  36,  66],
         ...,
         [162, 174, 162],
         [168, 178, 166],
         [170, 180, 168]],

        [[ 28,  36,  66],
         [ 28,  36,  66],
         [ 28,  36,  66],
         ...,
         [163, 176, 163],
         [168, 179, 167],
         [171, 181, 169]],

        [[ 28,  36,  66],
         [ 28,  36,  66],
         [ 28,  36,  66],
         ...,
         [163, 176, 164],
        

In [ ]:
y

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,

In [ ]:
X

array([[[[  3,   2,   4],
         [  3,   2,   4],
         [  3,   2,   4],
         ...,
         [ 11,   9,   9],
         [ 10,   8,   8],
         [ 10,   8,   8]],

        [[  3,   2,   4],
         [  3,   2,   4],
         [  4,   3,   5],
         ...,
         [ 11,   9,   9],
         [ 10,   8,   8],
         [ 10,   8,   8]],

        [[  3,   2,   4],
         [  3,   2,   4],
         [  4,   3,   5],
         ...,
         [ 11,   9,   9],
         [ 10,   8,   8],
         [ 10,   8,   8]],

        ...,

        [[ 28,  36,  66],
         [ 28,  36,  66],
         [ 28,  36,  66],
         ...,
         [162, 174, 162],
         [168, 178, 166],
         [170, 180, 168]],

        [[ 28,  36,  66],
         [ 28,  36,  66],
         [ 28,  36,  66],
         ...,
         [163, 176, 163],
         [168, 179, 167],
         [171, 181, 169]],

        [[ 28,  36,  66],
         [ 28,  36,  66],
         [ 28,  36,  66],
         ...,
         [163, 176, 164],
        

In [ ]:
X = X/255

In [ ]:
X

array([[[[0.01176471, 0.00784314, 0.01568627],
         [0.01176471, 0.00784314, 0.01568627],
         [0.01176471, 0.00784314, 0.01568627],
         ...,
         [0.04313725, 0.03529412, 0.03529412],
         [0.03921569, 0.03137255, 0.03137255],
         [0.03921569, 0.03137255, 0.03137255]],

        [[0.01176471, 0.00784314, 0.01568627],
         [0.01176471, 0.00784314, 0.01568627],
         [0.01568627, 0.01176471, 0.01960784],
         ...,
         [0.04313725, 0.03529412, 0.03529412],
         [0.03921569, 0.03137255, 0.03137255],
         [0.03921569, 0.03137255, 0.03137255]],

        [[0.01176471, 0.00784314, 0.01568627],
         [0.01176471, 0.00784314, 0.01568627],
         [0.01568627, 0.01176471, 0.01960784],
         ...,
         [0.04313725, 0.03529412, 0.03529412],
         [0.03921569, 0.03137255, 0.03137255],
         [0.03921569, 0.03137255, 0.03137255]],

        ...,

        [[0.10980392, 0.14117647, 0.25882353],
         [0.10980392, 0.14117647, 0.25882353]

In [ ]:
X.shape

(994, 224, 224, 3)

In [ ]:
X.shape

(994, 224, 224, 3)

In [ ]:
Y=y.reshape(y.shape[0],1,1,)

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten,GlobalAveragePooling2D
from tensorflow.keras.models import Model



In [ ]:
from tensorflow.keras.applications.vgg19 import VGG19

base_model = VGG19(
    include_top=False,
    weights='imagenet',
    input_shape=(224,224,3)
)


80134624/80134624 [==============================] - 1s 0us/step


In [ ]:
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
predictions = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=predictions)

In [ ]:
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics = ['accuracy'])

In [ ]:
Y.shape

(994, 1, 1)

In [ ]:
model.fit(X, Y, epochs=5, validation_split=0.2)

Epoch 1/5
25/25 [==============================] - 48s 928ms/step - loss: 1.3171 - accuracy: 0.6478 - val_loss: 0.6168 - val_accuracy: 0.6985
Epoch 2/5
25/25 [==============================] - 12s 480ms/step - loss: 0.6181 - accuracy: 0.7019 - val_loss: 0.6123 - val_accuracy: 0.6985
Epoch 3/5
25/25 [==============================] - 12s 485ms/step - loss: 0.6125 - accuracy: 0.7019 - val_loss: 0.6186 - val_accuracy: 0.6985
Epoch 4/5
25/25 [==============================] - 12s 487ms/step - loss: 0.6127 - accuracy: 0.7019 - val_loss: 0.6137 - val_accuracy: 0.6985
Epoch 5/5
25/25 [==============================] - 12s 491ms/step - loss: 0.6749 - accuracy: 0.7019 - val_loss: 0.6193 - val_accuracy: 0.6985


In [ ]:
model.save('vgg19.model',save_format = 'h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
import numpy as np
import cv2
import keras

In [ ]:
#new_model = tf.keras.models.load_model('/content/drive/MyDrive/vgg19.model')

In [ ]:
def image(path):
    img = cv2.imread(path, cv2.IMREAD_COLOR)
    new_arr = cv2.resize(img, (224, 224))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 224,224, 3)
    return new_arr
#preprocessing the user input

model = keras.models.load_model('/content/vgg19.model')

result = model.predict([image('/content/newlal.jpg')])
if result[0][0] >0.9:
    prediction = 'mammooty'
else:
    prediction = 'mohanlal'
print(prediction)


1/1 [==============================] - 0s 157ms/step
mohanlal
