<a href="https://colab.research.google.com/github/Shilpa-PJ/DL-Projects/blob/main/vgg_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import cv2 as cv
import random
import os
import matplotlib.pyplot as plt
import pickle
import keras
%matplotlib inline


In [ ]:
DIRECTORY =  '/content/drive/MyDrive/dataset'
# a raw string(r'...') is used to treat backslash(\) as a normal character
CATEGORIES = ['mammooty','mohanlal']


In [ ]:
IMG_SIZE = 224

data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        label = CATEGORIES.index(category)
        img_arr = cv.imread(img_path)
        img_arr = cv.resize(img_arr,(IMG_SIZE,IMG_SIZE))
        data.append([img_arr,label])
#         labelling the data

In [ ]:
import random
random.shuffle(data)

In [ ]:
X = []
y = []

for features, labels in data:
    X.append(features)
    y.append(labels)

In [ ]:
X = np.array(X)
y = np.array(y)
# changed X & y into arrays and stored it in respective variables

In [ ]:
X

array([[[[127, 125, 137],
         [126, 124, 137],
         [126, 124, 136],
         ...,
         [ 13,  13,  13],
         [ 13,  13,  13],
         [ 13,  13,  13]],

        [[126, 125, 137],
         [126, 124, 136],
         [126, 124, 136],
         ...,
         [ 13,  13,  13],
         [ 13,  13,  13],
         [ 13,  13,  13]],

        [[126, 124, 136],
         [126, 124, 136],
         [126, 124, 136],
         ...,
         [ 14,  14,  14],
         [ 14,  14,  14],
         [ 14,  14,  14]],

        ...,

        [[117, 115, 127],
         [117, 115, 127],
         [118, 116, 128],
         ...,
         [ 95, 105, 247],
         [ 95, 105, 246],
         [ 96, 105, 246]],

        [[117, 115, 127],
         [117, 115, 127],
         [118, 116, 128],
         ...,
         [ 95, 105, 245],
         [ 95, 105, 245],
         [ 96, 105, 244]],

        [[117, 115, 127],
         [117, 115, 127],
         [118, 116, 128],
         ...,
         [ 95, 106, 244],
        

In [ ]:
y

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,

In [ ]:
X

array([[[[127, 125, 137],
         [126, 124, 137],
         [126, 124, 136],
         ...,
         [ 13,  13,  13],
         [ 13,  13,  13],
         [ 13,  13,  13]],

        [[126, 125, 137],
         [126, 124, 136],
         [126, 124, 136],
         ...,
         [ 13,  13,  13],
         [ 13,  13,  13],
         [ 13,  13,  13]],

        [[126, 124, 136],
         [126, 124, 136],
         [126, 124, 136],
         ...,
         [ 14,  14,  14],
         [ 14,  14,  14],
         [ 14,  14,  14]],

        ...,

        [[117, 115, 127],
         [117, 115, 127],
         [118, 116, 128],
         ...,
         [ 95, 105, 247],
         [ 95, 105, 246],
         [ 96, 105, 246]],

        [[117, 115, 127],
         [117, 115, 127],
         [118, 116, 128],
         ...,
         [ 95, 105, 245],
         [ 95, 105, 245],
         [ 96, 105, 244]],

        [[117, 115, 127],
         [117, 115, 127],
         [118, 116, 128],
         ...,
         [ 95, 106, 244],
        

In [ ]:
X = X/255

In [ ]:
X

array([[[[0.49803922, 0.49019608, 0.5372549 ],
         [0.49411765, 0.48627451, 0.5372549 ],
         [0.49411765, 0.48627451, 0.53333333],
         ...,
         [0.05098039, 0.05098039, 0.05098039],
         [0.05098039, 0.05098039, 0.05098039],
         [0.05098039, 0.05098039, 0.05098039]],

        [[0.49411765, 0.49019608, 0.5372549 ],
         [0.49411765, 0.48627451, 0.53333333],
         [0.49411765, 0.48627451, 0.53333333],
         ...,
         [0.05098039, 0.05098039, 0.05098039],
         [0.05098039, 0.05098039, 0.05098039],
         [0.05098039, 0.05098039, 0.05098039]],

        [[0.49411765, 0.48627451, 0.53333333],
         [0.49411765, 0.48627451, 0.53333333],
         [0.49411765, 0.48627451, 0.53333333],
         ...,
         [0.05490196, 0.05490196, 0.05490196],
         [0.05490196, 0.05490196, 0.05490196],
         [0.05490196, 0.05490196, 0.05490196]],

        ...,

        [[0.45882353, 0.45098039, 0.49803922],
         [0.45882353, 0.45098039, 0.49803922]

In [ ]:
X.shape

(994, 224, 224, 3)

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten,GlobalAveragePooling2D
from tensorflow.keras.models import Model



In [ ]:
from tensorflow.keras.applications.vgg16 import VGG16

base_model = VGG16(
    include_top=False,
    weights='imagenet',
    input_shape=(224,224,3)
)


58889256/58889256 [==============================] - 3s 0us/step


In [ ]:
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
predictions = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=predictions)

In [ ]:
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics = ['accuracy'])

In [ ]:
y.shape

(994,)

In [ ]:
model.fit(X, y, epochs=5, validation_split=0.2)

Epoch 1/5
25/25 [==============================] - 46s 867ms/step - loss: 9.9627 - accuracy: 0.6566 - val_loss: 0.6405 - val_accuracy: 0.6734
Epoch 2/5
25/25 [==============================] - 10s 395ms/step - loss: 0.6128 - accuracy: 0.7082 - val_loss: 0.6321 - val_accuracy: 0.6734
Epoch 3/5
25/25 [==============================] - 10s 394ms/step - loss: 0.6080 - accuracy: 0.7082 - val_loss: 0.6366 - val_accuracy: 0.6734
Epoch 4/5
25/25 [==============================] - 10s 421ms/step - loss: 0.6056 - accuracy: 0.7082 - val_loss: 0.6296 - val_accuracy: 0.6734
Epoch 5/5
25/25 [==============================] - 10s 422ms/step - loss: 0.6058 - accuracy: 0.7082 - val_loss: 0.6301 - val_accuracy: 0.6734


In [ ]:
model.save('vgg16.model',save_format = 'h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
import numpy as np
import cv2
import keras

In [ ]:
def image(path):
    img = cv2.imread(path, cv2.IMREAD_COLOR)
    new_arr = cv2.resize(img, (224, 224))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 224,224, 3)
    return new_arr
#preprocessing the user input

model = keras.models.load_model('/content/vgg16.model')

result = model.predict([image('/content/newlal.jpg')])
if result[0][0] >0.9:
    prediction = 'mamooty'
else:
    prediction = 'mohanlal'

print(prediction)

1/1 [==============================] - 1s 742ms/step
mohanlal
